### ISSUE TITLE
action

### ISSUE THREAD

**Issue by zero150717** [luoboQuQ/PyAipao#6]
GitHub Actions Auto Run: All jobs have failed
 
View workflow run
 
￼	
GitHub Actions Auto Run / bot
Failed in 54 seconds

麻烦这是啥情况，还有咋实现多用户哇

**Comment by luoboQuQ** [comment]
1.错误信息可以在Actions里看到，一般是IMEIcode失效或者是推送设置错误。
2.为了避免为他人代跑谋利，暂时不打算支持多用户。
